### ISSUE TITLE
Hi! Could I use your code?

### ISSUE THREAD

**Issue by xuanyuwang** [mld2443/Sudoku#1]
If there is a way to use your code in a no-commercial and no offence way? There is an assignment which major in the interaction between user and app, could I use your code to generate a sudoku puzzle? Thank you!

**Comment by mld2443** [comment]
Sure, if you must use swift, then go right ahead. If you would like to know of a better open source sudoku puzzle generator that's not necessarily in Swift, then might I suggest Simon Tatham's implementation of sudoku [here](https://git.tartarus.org/?p=simon/puzzles.git), titled Solo.

Sorry for my tardiness, I meant to reply sooner but got distracted.

**Comment by xuanyuwang** [comment]
Thank you very much. Your way to generate a sudoku puzzle is efficient and the metric of difficulty is great. I am going to check the link you recommended.

On Tue, 18 Oct 2016 at 16:19 Matt <notifications@github.com<mailto:notifications@github.com>> wrote:

Sure, if you must use swift, then go right ahead. If you would like to know of a better open source sudoku puzzle generator that's not necessarily in Swift, then might I suggest Simon Tatham's implementation of sudoku herehttps://git.tartarus.org/?p=simon/puzzles.git, titled Solo.

Sorry for my tardiness, I meant to reply sooner but got distracted.

**Comment by mld2443** [comment]
Simon's method is far more complex, but is also far more robust and versatile. It can generate puzzles of varying sizes, difficulties, and types without relying on a bank of pre-loaded puzzles like mine does.
